### ISSUE TITLE
Wrong natural channel schematic.

### ISSUE THREAD

**Issue by Mysonemo** [maestun/darkterrormods#1]
On the readme it's written "Lift one terminal of the R20 resistor (the one connected to ground)".
On the schema there is no reference to R20 but to R14 / VR3 pin 2.

Regarding 6.3v we go on the yellow like the led i think ?

**Comment by maestun** [comment]
Could you please provide a link to the schematic you are using ?
I remember using this one: http://guitar-fx-layouts.42897.x6.nabble.com/file/n24330/darkterror2%25281%2529.png
The R20 resistor is located after the volume pot.

For the 6.3v, you're right: you can use either the bulb's or a tube heater's yellow wire (there's no LED in that amp).

**Comment by Mysonemo** [comment]
I'm using the same but I was speaking about this schema https://github.com/maestun/darkterrormods/blob/master/natural_channel.png
the one you provided for natural channel.

Regarding the 6.3v, yes I wanted to say the  bulbs. 

By the way. Thank you for your reply. It's appreciated. 😉

**Comment by maestun** [comment]
You are right, the "to R14 / VR3 pin 2" annotation on my schematic looks wrong.
Please let me check that again and I'll commit the fix asap.

**Comment by Mysonemo** [comment]
I think there is another issue on this schematic. On the RY1 you inverted the relay to the natural channel and to the R20 (I supposed). 
![Screenshot_20200601_142910_com android chrome~3](https://user-images.githubusercontent.com/19433015/83410955-9d63fc00-a417-11ea-90e8-1f4ccd1dd8df.jpg)



Also why did you added the 47R to the ground ?

**Comment by Mysonemo** [comment]
Also I build it, the relay is switching well but no sound 😬. Can you confirm the schema. Also if you have some pictures of your's

**Comment by maestun** [comment]
Sorry, I have no pics of mine.
Regarding the audio path, the schematic above should be correct.
The natural channel is located between R3 and R20: it uses only the 1st triode and bypasses the 3 others. The Natural Channel schematic is basically a gain/volume control.

Please check the Rocker 30 Natural Channel schematic as reference: it is basically what I reproduced here with the relay.

**Comment by Mysonemo** [comment]
So it's R20 right ? Not to R14 / VR3 pin 2

**Comment by Mysonemo** [comment]
Maybe my issue is on the wording. When you say lift C2 and R20 you mean desolder, right ?

**Comment by Mysonemo** [comment]
> Sorry, I have no pics of mine.
> Regarding the audio path, the schematic above should be correct.
> The natural channel is located between R3 and R20: it uses only the 1st triode and bypasses the 3 others. The Natural Channel schematic is basically a gain/volume control.
> 
> Please check the Rocker 30 Natural Channel schematic as reference: it is basically what I reproduced here with the relay.

I'm checking the Rocker 30, that part is ok. It's just that i've the impression that the second switch of the relay is in the wrong state.

**Comment by maestun** [comment]
> Maybe my issue is on the wording. When you say lift C2 and R20 you mean desolder, right ?
Yes.

**Comment by maestun** [comment]
> Maybe my issue is on the wording. When you say lift C2 and R20 you mean desolder, right ?

Yes

**Comment by Mysonemo** [comment]
I just took the schema and updated it. Can you confirm ?
![darkterror2%281%29](https://user-images.githubusercontent.com/19433015/83446675-627dba80-a44f-11ea-91e3-703dbbde3b69.png)

**Comment by Mysonemo** [comment]
But that mean that 100K and 47R are useless so i think there is mistake or something missing. It should be like that. 
![image](https://user-images.githubusercontent.com/19433015/83456637-577f5600-a460-11ea-8cf7-4aafdf1d80da.png)

**Comment by Mysonemo** [comment]
Ok my issue was on the potentiometer ... So I fixed it and I'm able to have sound with the switch. But It look like a ground is missing somewhere. Can I use the same ground for both in the schema ?

**Comment by maestun** [comment]
The 1st half of the relay wiring (next to V1A) is OK, but not the 2nd.
Fault is on me, sorry.
I've redrawn the wiring with potato quality:

![IMG_3613](https://user-images.githubusercontent.com/8136742/83612927-5bf05f80-a583-11ea-929b-eae792977967.JPG)

![IMG_3615](https://user-images.githubusercontent.com/8136742/83612923-5a269c00-a583-11ea-9007-171574ab412d.JPG)

As you can see, the goal of the 1st half of the relay is to select the channel. I've added an optional 'anti-pop' resistor, but you can omit it (I did).
The 2nd half sets the output of the unselected channel to ground (through a 47R resistor, like in the Rockerverb 50 schematic), *and* also inverts the resistor divider made by R19 and R20.

Looks like you have some more soldering to do, good luck :)

I'm leaving this issue open until I draw nicer schematics.

**Comment by Mysonemo** [comment]
> The 1st half of the relay wiring (next to V1A) is OK, but not the 2nd.
> Fault is on me, sorry.
> I've redrawn the wiring with potato quality:
> 
> ![IMG_3613](https://user-images.githubusercontent.com/8136742/83612927-5bf05f80-a583-11ea-929b-eae792977967.JPG)
> 
> ![IMG_3615](https://user-images.githubusercontent.com/8136742/83612923-5a269c00-a583-11ea-9007-171574ab412d.JPG)
> 
> As you can see, the goal of the 1st half of the relay is to select the channel. I've added an optional 'anti-pop' resistor, but you can omit it (I did).
> The 2nd half sets the output of the unselected channel to ground (through a 47R resistor, like in the Rockerverb 50 schematic), _and_ also inverts the resistor divider made by R19 and R20.
> 
> Looks like you have some more soldering to do, good luck :)
> 
> I'm leaving this issue open until I draw nicer schematics.

Testing this afternoon. I will reply soon.

**Comment by Mysonemo** [comment]
> The 1st half of the relay wiring (next to V1A) is OK, but not the 2nd.
> Fault is on me, sorry.
> I've redrawn the wiring with potato quality:
> 
> ![IMG_3613](https://user-images.githubusercontent.com/8136742/83612927-5bf05f80-a583-11ea-929b-eae792977967.JPG)
> 
> ![IMG_3615](https://user-images.githubusercontent.com/8136742/83612923-5a269c00-a583-11ea-9007-171574ab412d.JPG)
> 
> As you can see, the goal of the 1st half of the relay is to select the channel. I've added an optional 'anti-pop' resistor, but you can omit it (I did).
> The 2nd half sets the output of the unselected channel to ground (through a 47R resistor, like in the Rockerverb 50 schematic), _and_ also inverts the resistor divider made by R19 and R20.
> 
> Looks like you have some more soldering to do, good luck :)
> 
> I'm leaving this issue open until I draw nicer schematics.

The 100k resistor is no more in ?

**Comment by maestun** [comment]
> The 100k resistor is no more in ?

Yes I removed it, I think that was a mistake.

**Comment by Mysonemo** [comment]
> > The 1st half of the relay wiring (next to V1A) is OK, but not the 2nd.
> > Fault is on me, sorry.
> > I've redrawn the wiring with potato quality:
> > ![IMG_3613](https://user-images.githubusercontent.com/8136742/83612927-5bf05f80-a583-11ea-929b-eae792977967.JPG)
> > ![IMG_3615](https://user-images.githubusercontent.com/8136742/83612923-5a269c00-a583-11ea-9007-171574ab412d.JPG)
> > As you can see, the goal of the 1st half of the relay is to select the channel. I've added an optional 'anti-pop' resistor, but you can omit it (I did).
> > The 2nd half sets the output of the unselected channel to ground (through a 47R resistor, like in the Rockerverb 50 schematic), _and_ also inverts the resistor divider made by R19 and R20.
> > Looks like you have some more soldering to do, good luck :)
> > I'm leaving this issue open until I draw nicer schematics.
> 
> The 100k resistor is no more in ?

So you checked in your amp ?
Because it's still not ok my side. I'm doing additional control right now.

**Comment by Mysonemo** [comment]
In fact on the natural channel I have sound but with a buzz and on dark channel ive no sound not even a buzz

**Comment by Mysonemo** [comment]
I found that R20 and R19 are In Parralel and visually I cannot see why

**Comment by Mysonemo** [comment]
R20 is 130k and R19 150k ... Super strange

**Comment by Mysonemo** [comment]
Where are you taking the ground ? To the one written in the middle ?

**Comment by Mysonemo** [comment]
I'm still stuck. Can it be caused by the wiring of the potentiometer ?

**Comment by Mysonemo** [comment]
I had an issue I'm close to fix it

**Comment by Mysonemo** [comment]
> In fact on the natural channel I have sound but with a buzz and on dark channel ive no sound not even a buzz

No idea ?

**Comment by Mysonemo** [comment]
> In fact on the natural channel I have sound but with a buzz and on dark channel ive no sound not even a buzz

I've sound on dark channel, like normal but on the natural channel lot of buzz. Any idea ?

**Comment by Mysonemo** [comment]
I re did all control and i'm stuck. Did you do exactly that in your amp ?

**Comment by Mysonemo** [comment]
Are you sure about the first part ? Taking on v1a directly and not after R5 (as the rockreverb 50) ?

**Comment by Mysonemo** [comment]
Shouldn't be better like that ?
![darkterror2%281%29](https://user-images.githubusercontent.com/19433015/84236150-78e2e080-aaf7-11ea-9c37-b4d1473baf54.png)

**Comment by maestun** [comment]
Yes, you can build it this way, it'll work: however the voltage divider formed by and R19 and R20 might "tame" the natural channel a bit too much. 
The 2nd hand-drawn schematic I've posted fixes that issue by "reversing" R19 and R20 when switching channels. It also sets the output of the unselected channel to ground thru a 47 ohm resistor.

**Comment by Mysonemo** [comment]
Ok so it's done exactly like your schematic but I'm still having big buzz on natural channel. I think a detail still missing. Any idea ?

**Comment by Mysonemo** [comment]
Maybe if you have pictures. It could help

**Comment by Mysonemo** [comment]
I did a stripboard is it possible that we have some interfer with the relay part ?

**Comment by Mysonemo** [comment]
Do you know where this buzz can come ? It looks like a ground issue. Can it be due to cable quality inside the amp ?

**Comment by maestun** [comment]
Cannot tell where the buzz comes from. Shouldn't be due to relay interference, since it uses direct current for switching. Probably a grounding issue, as you say.
I've checked the mod on my own amp, it matches the schematics I've sent you. You should check again everything.

**Comment by Mysonemo** [comment]
When I'm switching to natural sound if I remove R19 to the 47R resistor it's changing nothing. Is it normal ?

**Comment by Mysonemo** [comment]
So did it again for the 5th time and changing all the components by new ones and still the same. I'm sorry something is missing in this diagram.
Or maybe components have a wrong value.

**Comment by Mysonemo** [comment]
I think it is on my stripboard. I will check that in 2 weeks as I'm leaving. I will keep you posted.

**Comment by Mysonemo** [comment]
I redid everything and I'm still having the buzz. issue isn't on stripboard. So I'm again stuck. Th 2m2 antipop maybe ??

**Comment by Mysonemo** [comment]
Can it be due because I have 6v in the relay instead of 5v ?

**Comment by Mysonemo** [comment]
> Can it be due because I have 6v in the relay instead of 5v ?

I fixed this by putting a 47R instead or 33R.

**Comment by Mysonemo** [comment]
I will jump to my first question. Where did you take 6.3 ? You said Yellow wire on bulb. but i should take the yellow and the black or 2 yellow from 2 different bulbs ?

**Comment by Mysonemo** [comment]
I'm trying to check all possibility. Because from now it still wrong for me.

**Comment by Mysonemo** [comment]
It's normal that I'm having contact between the positive 6v and the ground ?
